### ISSUE TITLE
Does this crate implement RFC3394?

### ISSUE THREAD

**Issue by hwiorn** [jedisct1/rust-aes-keywrap#2]
> This is an AES-KW (RFC 3394 / RFC 5649) implementation for Rust.

I thought this crate had implemented [RFC3394](http://www.ietf.org/rfc/rfc3394.txt). I tested RFC3394 test-vectors, but the test got always `AuthenticationFailed`. 
I compared this crate and the [aes_keywrap](https://github.com/kurtbrose/aes_keywrap/blob/master/aes_keywrap.py) module of Python. And I found out this crate implemented only [RFC5649](http://www.ietf.org/rfc/rfc5649.txt).

```rust
    let mut kek: [u8; 16] = [0; 16];
    hex::decode_to_slice("000102030405060708090A0B0C0D0E0F", &mut kek).expect("");
    let cipher = hex::decode("1FA68B0A8112B447AEF34BD8FB5A7B829D3E862371D2CFE5").expect("");
    let plain = hex::decode("00112233445566778899AABBCCDDEEFF").expect("");
    let aes_kw = Aes128KeyWrap::new(&kek);
    assert_eq!(cipher, aes_kw.encapsulate(&plain).unwrap()); // Got assertion failed.
    assert_eq!(plain, aes_kw.decapsulate(&cipher, kek.len()).unwrap()); // Got authentication failed.
```

Could you check this out?

**Comment by jedisct1** [comment]
The reference to RFC3394 has been removed, thanks!
